/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as CanvasIdRouteImport } from './routes/canvas.$id'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIdRoute = CanvasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CanvasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/canvas/$id': typeof CanvasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/canvas/$id': typeof CanvasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/login': typeof LoginRoute
  '/api/$': typeof ApiSplatRoute
  '/canvas/$id': typeof CanvasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/canvas' | '/login' | '/api/$' | '/canvas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/canvas' | '/login' | '/api/$' | '/canvas/$id'
  id: '__root__' | '/' | '/canvas' | '/login' | '/api/$' | '/canvas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$id': {
      id: '/canvas/$id'
      path: '/$id'
      fullPath: '/canvas/$id'
      preLoaderRoute: typeof CanvasIdRouteImport
      parentRoute: typeof CanvasRoute
    }
  }
}

interface CanvasRouteChildren {
  CanvasIdRoute: typeof CanvasIdRoute
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasIdRoute: CanvasIdRoute,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { createStart } from '@tanstack/react-start'

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
