// Generated by bunderstack codegen from /api/openapi.json.
// Owned by you: edit, trim, or regenerate freely.
const BASE_URL = ""

export type UndefinedError = { "defined": false; "inferable": boolean; "code": string; "status": number; "message": string; "data"?: unknown }
export type BadRequest = { "defined": true; "inferable": boolean; "code": "BAD_REQUEST"; "status": 400; "message": string; "data": { "code"?: "BAD_REQUEST"; "details"?: unknown } }
export type Unauthorized = { "defined": true; "inferable": boolean; "code": "UNAUTHORIZED"; "status": 401; "message": string; "data": { "code"?: "UNAUTHORIZED"; "details"?: unknown } }
export type Forbidden = { "defined": true; "inferable": boolean; "code": "FORBIDDEN"; "status": 403; "message": string; "data": { "code"?: "FORBIDDEN"; "details"?: unknown } }
export type NotFound = { "defined": true; "inferable": boolean; "code": "NOT_FOUND"; "status": 404; "message": string; "data": { "code"?: "NOT_FOUND"; "details"?: unknown } }
export type Conflict = { "defined": true; "inferable": boolean; "code": "CONFLICT"; "status": 409; "message": string; "data": { "code"?: "CONFLICT"; "details"?: unknown } }
export type PayloadTooLarge = { "defined": true; "inferable": boolean; "code": "PAYLOAD_TOO_LARGE"; "status": 413; "message": string; "data": { "code"?: "PAYLOAD_TOO_LARGE"; "details"?: unknown } }
export type TooManyRequests = { "defined": true; "inferable": boolean; "code": "TOO_MANY_REQUESTS"; "status": 429; "message": string; "data": { "code"?: "TOO_MANY_REQUESTS"; "details"?: unknown } }
export type User = { "id": string; "name": string; "email": string; "emailVerified": boolean; "image"?: string; "createdAt": string; "updatedAt": string }
export type Session = { "id": string; "expiresAt": string; "token": string; "createdAt": string; "updatedAt": string; "ipAddress"?: string; "userAgent"?: string; "userId": string }
export type Account = { "id": string; "accountId": string; "providerId": string; "userId": string; "accessToken"?: string; "refreshToken"?: string; "idToken"?: string; "accessTokenExpiresAt"?: string; "refreshTokenExpiresAt"?: string; "scope"?: string; "password"?: string; "createdAt": string; "updatedAt": string }
export type Verification = { "id": string; "identifier": string; "value": string; "expiresAt": string; "createdAt": string; "updatedAt": string }


async function requestJson(url: string, init?: RequestInit): Promise<unknown> {
  const response = await fetch(url, init)
  if (!response.ok) throw new Error(response.status + ' ' + (await response.text()))
  if (response.status === 204) return undefined
  return response.json()
}

function withQuery(url: string, input?: Record<string, unknown>): string {
  if (!input) return url
  const params = new URLSearchParams()
  for (const [key, value] of Object.entries(input)) {
    if (value === undefined) continue
    params.set(key, typeof value === 'string' ? value : JSON.stringify(value))
  }
  return params.size ? url + '?' + params : url
}


// Inlined from bunderstack's live-view contract: frames are SSE events whose
// data is JSON; keepalive comments never surface here. Typed as any so the
// wrapper below can narrow to the operation's own frame union.
async function* sseFrames(url: string, signal: AbortSignal): AsyncGenerator<any> {
  const response = await fetch(url, { signal, headers: { accept: 'text/event-stream' } })
  if (!response.ok || !response.body) throw new Error('Live request failed (' + response.status + ')')
  const reader = response.body.pipeThrough(new TextDecoderStream()).getReader()
  let buffer = ''
  let data: string[] = []
  const flush = (): unknown => {
    if (data.length === 0) return undefined
    const parsed = JSON.parse(data.join('\n'))
    data = []
    return parsed
  }
  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      buffer += value
      let newline: number
      while ((newline = buffer.indexOf('\n')) !== -1) {
        const line = buffer.slice(0, newline)
        buffer = buffer.slice(newline + 1)
        if (line === '') {
          const frame = flush()
          if (frame !== undefined) yield frame
        } else if (line.startsWith('data: ')) {
          data.push(line.slice(6))
        }
      }
    }
    const frame = flush()
    if (frame !== undefined) yield frame
  } finally {
    await reader.cancel().catch(() => {})
  }
}

export async function healthList(
): Promise<{ "status": "ok" }> {
  const url = withQuery(BASE_URL + "/api/health", undefined)
  return requestJson(url, { method: "GET" }) as never
}

export async function todosList(
  input?: { "limit"?: number; "offset"?: number; "cursor"?: string; "sort"?: "createdAt" | "done"; "order"?: "asc" | "desc"; "q"?: string; "count"?: boolean; "filters"?: Record<string, never> },
): Promise<{ "items": { "id": unknown; "title": string; "done": boolean; "createdAt": string }[]; "nextCursor"?: string; "hasMore": boolean; "total"?: number; "limit"?: number; "offset"?: number; "cursor"?: string; "q"?: string; "sort"?: string; "order"?: string }> {
  const url = withQuery(BASE_URL + "/api/todos", input)
  return requestJson(url, { method: "GET" }) as never
}

export async function todosCreate(
  body: { "id"?: unknown; "title": string; "done"?: boolean; "createdAt"?: string },
): Promise<{ "id": unknown; "title": string; "done": boolean; "createdAt": string }> {
  const url = withQuery(BASE_URL + "/api/todos", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function todosGet(
  id: string,
): Promise<{ "id": unknown; "title": string; "done": boolean; "createdAt": string }> {
  const url = withQuery(BASE_URL + "/api/todos/{id}".replace('{id}', encodeURIComponent(String(id))), undefined)
  return requestJson(url, { method: "GET" }) as never
}

export async function todosUpdate(
  id: string,
  body: { "title"?: string; "done"?: boolean; "createdAt"?: string },
): Promise<{ "id": unknown; "title": string; "done": boolean; "createdAt": string }> {
  const url = withQuery(BASE_URL + "/api/todos/{id}".replace('{id}', encodeURIComponent(String(id))), undefined)
  return requestJson(url, { method: "PATCH", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function todosDelete(
  id: string,
): Promise<void> {
  const url = withQuery(BASE_URL + "/api/todos/{id}".replace('{id}', encodeURIComponent(String(id))), undefined)
  return requestJson(url, { method: "DELETE" }) as never
}

export async function* todosLive(
  input?: { "limit"?: number; "sort"?: "createdAt" | "done"; "order"?: "asc" | "desc"; "filters"?: Record<string, never> },
  signal?: AbortSignal,
): AsyncIterable<({ "type": "snapshot"; "items": Record<string, unknown>[]; "sort"?: string; "order"?: "asc" | "desc"; "limit"?: number } | { "type": "upsert"; "record": Record<string, unknown> } | { "type": "remove"; "id": string } | { "type": "heartbeat"; "intervalMs": number })> {
  const url = withQuery(BASE_URL + "/api/todos/live", input)
  yield* sseFrames(url, signal ?? new AbortController().signal)
}

export async function filesDefaultPresignCreate(
  body: { "filename"?: string; "contentType"?: string },
): Promise<({ "mode": "proxy"; "uploadUrl": string } | { "mode": "presign"; "fileId": string; "uploadUrl": string; "method": "PUT"; "confirmUrl": string })> {
  const url = withQuery(BASE_URL + "/api/files/default/presign", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function filesDefaultCreate(
  body: { "file": unknown },
): Promise<{ "fileId": string; "url": string }> {
  const url = withQuery(BASE_URL + "/api/files/default", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function filesDefaultConfirmCreate(
  id: string,
  body: Record<string, unknown>,
): Promise<{ "fileId": string; "url": string }> {
  const url = withQuery(BASE_URL + "/api/files/default/{id}/confirm".replace('{id}', encodeURIComponent(String(id))), undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function filesDefaultGet(
  id: string,
): Promise<void> {
  const url = withQuery(BASE_URL + "/api/files/default/{path}".replace('{id}', encodeURIComponent(String(id))), undefined)
  return requestJson(url, { method: "GET" }) as never
}

export async function filesDefaultDelete(
  id: string,
): Promise<void> {
  const url = withQuery(BASE_URL + "/api/files/default/{path}".replace('{id}', encodeURIComponent(String(id))), undefined)
  return requestJson(url, { method: "DELETE" }) as never
}

export async function* realtimeList(
  input?: { "tables"?: (string | string[]) },
  signal?: AbortSignal,
): AsyncIterable<({ "table": string; "action": "create" | "update" | "delete"; "record": Record<string, unknown> } | { "type": "heartbeat"; "intervalMs": number })> {
  const url = withQuery(BASE_URL + "/api/realtime", input)
  yield* sseFrames(url, signal ?? new AbortController().signal)
}

export async function authSignInSocialCreate(
  body: { "callbackURL"?: string; "newUserCallbackURL"?: string; "errorCallbackURL"?: string; "provider": ("apple" | "atlassian" | "cognito" | "discord" | "facebook" | "figma" | "github" | "microsoft" | "google" | "huggingface" | "slack" | "spotify" | "twitch" | "twitter" | "dropbox" | "kick" | "linear" | "linkedin" | "gitlab" | "tiktok" | "reddit" | "roblox" | "salesforce" | "vk" | "zoom" | "notion" | "kakao" | "naver" | "line" | "paybin" | "paypal" | "polar" | "railway" | "vercel" | "wechat" | string); "disableRedirect"?: boolean; "idToken"?: { "token": string; "nonce"?: string; "accessToken"?: string; "refreshToken"?: string; "expiresAt"?: number; "user"?: { "name"?: { "firstName"?: string; "lastName"?: string }; "email"?: string } }; "scopes"?: string[]; "requestSignUp"?: boolean; "loginHint"?: string; "additionalData"?: Record<string, unknown> },
): Promise<{ "token"?: string; "user"?: User; "url"?: string; "redirect": boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/sign-in/social", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authCallbackGet(
  id: string,
): Promise<void> {
  const url = withQuery(BASE_URL + "/api/auth/callback/{id}".replace('{id}', encodeURIComponent(String(id))), undefined)
  return requestJson(url, { method: "GET" }) as never
}

export async function authCallbackCreate(
  id: string,
  body: { "code"?: string; "error"?: string; "device_id"?: string; "error_description"?: string; "state"?: string; "user"?: string },
): Promise<void> {
  const url = withQuery(BASE_URL + "/api/auth/callback/{id}".replace('{id}', encodeURIComponent(String(id))), undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authGetSession(
): Promise<object | null> {
  const url = withQuery(BASE_URL + "/api/auth/get-session", undefined)
  return requestJson(url, { method: "GET" }) as never
}

export async function authGetSessionCreate(
  body: Record<string, unknown>,
): Promise<object | null> {
  const url = withQuery(BASE_URL + "/api/auth/get-session", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authSignOutCreate(
  body: Record<string, unknown>,
): Promise<{ "success"?: boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/sign-out", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authSignUpEmailCreate(
  body: { "name": string; "email": string; "password": string; "image"?: string; "callbackURL"?: string; "rememberMe"?: boolean },
): Promise<{ "token"?: string; "user": { "id": string; "email": string; "name": string; "image"?: string; "emailVerified": boolean; "createdAt": string; "updatedAt": string } }> {
  const url = withQuery(BASE_URL + "/api/auth/sign-up/email", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authSignInEmailCreate(
  body: { "email": string; "password": string; "callbackURL"?: string; "rememberMe"?: boolean },
): Promise<{ "redirect": false; "token": string; "url"?: string; "user": User }> {
  const url = withQuery(BASE_URL + "/api/auth/sign-in/email", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authResetPasswordCreate(
  body: { "newPassword": string; "token"?: string },
): Promise<{ "status"?: boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/reset-password", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authVerifyPasswordCreate(
  body: { "password": string },
): Promise<{ "status"?: boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/verify-password", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authVerifyEmail(
  input?: { "token"?: string; "callbackURL"?: string },
): Promise<{ "user": User; "status": boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/verify-email", input)
  return requestJson(url, { method: "GET" }) as never
}

export async function authSendVerificationEmailCreate(
  body: { "email": string; "callbackURL"?: string },
): Promise<{ "status"?: boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/send-verification-email", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authChangeEmailCreate(
  body: { "newEmail": string; "callbackURL"?: string },
): Promise<{ "user"?: User; "status": boolean; "message"?: "Email updated" | "Verification email sent" }> {
  const url = withQuery(BASE_URL + "/api/auth/change-email", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authChangePasswordCreate(
  body: { "newPassword": string; "currentPassword": string; "revokeOtherSessions"?: boolean },
): Promise<{ "token"?: string; "user": { "id": string; "email": string; "name": string; "image"?: string; "emailVerified": boolean; "createdAt": string; "updatedAt": string } }> {
  const url = withQuery(BASE_URL + "/api/auth/change-password", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authUpdateSessionCreate(
  body: Record<string, unknown>,
): Promise<{ "session"?: Session }> {
  const url = withQuery(BASE_URL + "/api/auth/update-session", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authUpdateUserCreate(
  body: { "name"?: string; "image"?: string },
): Promise<{ "user"?: User }> {
  const url = withQuery(BASE_URL + "/api/auth/update-user", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authDeleteUserCreate(
  body: { "callbackURL"?: string; "password"?: string; "token"?: string },
): Promise<{ "success": boolean; "message": "User deleted" | "Verification email sent" }> {
  const url = withQuery(BASE_URL + "/api/auth/delete-user", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authRequestPasswordResetCreate(
  body: { "email": string; "redirectTo"?: string },
): Promise<{ "status"?: boolean; "message"?: string }> {
  const url = withQuery(BASE_URL + "/api/auth/request-password-reset", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authResetPasswordGet(
  id: string,
  input?: { "callbackURL"?: string },
): Promise<{ "token"?: string }> {
  const url = withQuery(BASE_URL + "/api/auth/reset-password/{token}".replace('{id}', encodeURIComponent(String(id))), input)
  return requestJson(url, { method: "GET" }) as never
}

export async function authListSessions(
): Promise<Session[]> {
  const url = withQuery(BASE_URL + "/api/auth/list-sessions", undefined)
  return requestJson(url, { method: "GET" }) as never
}

export async function authRevokeSessionCreate(
  body: { "token": string },
): Promise<{ "status": boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/revoke-session", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authRevokeSessionsCreate(
  body: Record<string, unknown>,
): Promise<{ "status": boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/revoke-sessions", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authRevokeOtherSessionsCreate(
  body: Record<string, unknown>,
): Promise<{ "status": boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/revoke-other-sessions", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authLinkSocialCreate(
  body: { "callbackURL"?: string; "provider": ("apple" | "atlassian" | "cognito" | "discord" | "facebook" | "figma" | "github" | "microsoft" | "google" | "huggingface" | "slack" | "spotify" | "twitch" | "twitter" | "dropbox" | "kick" | "linear" | "linkedin" | "gitlab" | "tiktok" | "reddit" | "roblox" | "salesforce" | "vk" | "zoom" | "notion" | "kakao" | "naver" | "line" | "paybin" | "paypal" | "polar" | "railway" | "vercel" | "wechat" | string); "idToken"?: { "token": string; "nonce"?: string; "accessToken"?: string; "refreshToken"?: string; "scopes"?: string[] }; "requestSignUp"?: boolean; "scopes"?: string[]; "errorCallbackURL"?: string; "disableRedirect"?: boolean; "additionalData"?: Record<string, unknown> },
): Promise<{ "url"?: string; "redirect": boolean; "status"?: boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/link-social", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authListAccounts(
): Promise<{ "id": string; "providerId": string; "createdAt": string; "updatedAt": string; "accountId": string; "userId": string; "scopes": string[] }[]> {
  const url = withQuery(BASE_URL + "/api/auth/list-accounts", undefined)
  return requestJson(url, { method: "GET" }) as never
}

export async function authDeleteUserCallback(
  input?: { "token"?: string; "callbackURL"?: string },
): Promise<{ "success": boolean; "message": "User deleted" }> {
  const url = withQuery(BASE_URL + "/api/auth/delete-user/callback", input)
  return requestJson(url, { method: "GET" }) as never
}

export async function authUnlinkAccountCreate(
  body: { "providerId": string; "accountId"?: string },
): Promise<{ "status"?: boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/unlink-account", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authRefreshTokenCreate(
  body: { "providerId": string; "accountId"?: string; "userId"?: string },
): Promise<{ "tokenType"?: string; "idToken"?: string; "accessToken"?: string; "refreshToken"?: string; "accessTokenExpiresAt"?: string; "refreshTokenExpiresAt"?: string }> {
  const url = withQuery(BASE_URL + "/api/auth/refresh-token", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authGetAccessTokenCreate(
  body: { "providerId": string; "accountId"?: string; "userId"?: string },
): Promise<{ "tokenType"?: string; "idToken"?: string; "accessToken"?: string; "accessTokenExpiresAt"?: string }> {
  const url = withQuery(BASE_URL + "/api/auth/get-access-token", undefined)
  return requestJson(url, { method: "POST", headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }) as never
}

export async function authAccountInfo(
): Promise<{ "user": { "id": string; "name"?: string; "email"?: string; "image"?: string; "emailVerified": boolean }; "data": Record<string, unknown> }> {
  const url = withQuery(BASE_URL + "/api/auth/account-info", undefined)
  return requestJson(url, { method: "GET" }) as never
}

export async function authOk(
): Promise<{ "ok": boolean }> {
  const url = withQuery(BASE_URL + "/api/auth/ok", undefined)
  return requestJson(url, { method: "GET" }) as never
}

export async function authError(
): Promise<void> {
  const url = withQuery(BASE_URL + "/api/auth/error", undefined)
  return requestJson(url, { method: "GET" }) as never
}
