// @ts-nocheck -- skip type checking
import * as docs_8 from "../content/docs/thumbnails.mdx?collection=docs&hash=1782082023896"
import * as docs_7 from "../content/docs/storage.mdx?collection=docs&hash=1782082023896"
import * as docs_6 from "../content/docs/index.mdx?collection=docs&hash=1782082023896"
import * as docs_5 from "../content/docs/getting-started.mdx?collection=docs&hash=1782082023896"
import * as docs_4 from "../content/docs/framework-portability.mdx?collection=docs&hash=1782082023896"
import * as docs_3 from "../content/docs/crud.mdx?collection=docs&hash=1782082023896"
import * as docs_2 from "../content/docs/configuration.mdx?collection=docs&hash=1782082023896"
import * as docs_1 from "../content/docs/auth.mdx?collection=docs&hash=1782082023896"
import * as docs_0 from "../content/docs/api-reference.mdx?collection=docs&hash=1782082023896"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"api-reference.mdx","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/api-reference.mdx"}, data: docs_0 }, { info: {"path":"auth.mdx","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/auth.mdx"}, data: docs_1 }, { info: {"path":"configuration.mdx","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/configuration.mdx"}, data: docs_2 }, { info: {"path":"crud.mdx","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/crud.mdx"}, data: docs_3 }, { info: {"path":"framework-portability.mdx","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/framework-portability.mdx"}, data: docs_4 }, { info: {"path":"getting-started.mdx","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/getting-started.mdx"}, data: docs_5 }, { info: {"path":"index.mdx","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/index.mdx"}, data: docs_6 }, { info: {"path":"storage.mdx","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/storage.mdx"}, data: docs_7 }, { info: {"path":"thumbnails.mdx","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/thumbnails.mdx"}, data: docs_8 }], [{"info":{"path":"meta.json","absolutePath":"/Users/kirill/pet-projects/bunderstack/website/content/docs/meta.json"},"data":{"title":"Bunderstack","pages":["index","getting-started","configuration","crud","auth","storage","thumbnails","framework-portability","api-reference"]}}])